# Generated by Django 3.1.3 on 2020-11-15 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_post_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='approved',
            new_name='deleted',
        ),
    ]
